services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    env_file:
      - .env
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: always
    tty: true
    stdin_open: true
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "mc-monitor", "status", "--host", "localhost", "--port", "25565"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
